[package]
name = "oasis-rs"
version = "0.1.0"
edition = "2021"

[features]
no-std = []
loom = []

[dependencies]
cfg-if = "1.0.0"

[dev-dependencies]
loom = "0.5"
proptest-derive = "0.3"
proptest-state-machine = "0.1"
proptest = "1.0"
rand = "0.8"
